# Stage 1: build with Gradle
FROM gradle:8.2-jdk17 AS build
WORKDIR /app

# Копируем только содержимое текущей папки (в Jenkins это app/)
COPY --chown=gradle:gradle . .

# Делаем gradlew исполняемым и собираем проект без daemon
RUN chmod +x gradlew
RUN ./gradlew build --no-daemon

# Stage 2: runtime
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Копируем все JAR из build/libs
COPY --from=build /app/build/libs/ /app/

# Создаем пользователя для запуска приложения
RUN useradd -m springuser
USER springuser

# Экспонируем порт приложения
EXPOSE 8080

# HEALTHCHECK
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s CMD curl -f http://localhost:8080/actuator/health || exit 1

# Команда запуска приложения (замени на реальное имя jar)
ENTRYPOINT ["java","-jar","/app/demo-1.0.0.jar"]
